baseURL: "https://dalamgir.github.io/"
title: "Daiyan Alamgir's Blog"
theme: "PaperMod"
pagination:
  pagerSize: 10
languageCode: "en-us"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  defaultTheme: dark
  summaryLength: 24
  assets:
    css:
      - "css/override.css"
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: false
  comments: false

menu:
  main:
    - name: "Posts"
      url: "/"
      weight: 1
    - name: "RSS"
      url: "/index.xml"
      weight: 2

markup:
  highlight:
    noClasses: true
    style: "dracula"
    lineNos: false
    lineNumbersInTable: false
  goldmark:
    renderer:
      unsafe: true
